// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("RangerFSConsole")>]
[<assembly: AssemblyProductAttribute("RangerFS")>]
[<assembly: AssemblyDescriptionAttribute("Intervals for .NET")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "RangerFSConsole"
    let [<Literal>] AssemblyProduct = "RangerFS"
    let [<Literal>] AssemblyDescription = "Intervals for .NET"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
